name: Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:        
      - uses: actions/checkout@v4

      - name: GitHub Readme Stats Action
        uses: stats-organization/github-readme-stats-action@v1.1.0
        with:
          card: stats
          token: ${{ secrets.STATS_CARD_TOKEN }}
          options: username=${{ github.repository_owner }}&show_icons=true&theme=gruvbox
          path: profile/stats.svg
          
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README stats [skip ci]"
          file_pattern: 'profile/*.svg'
